spring:
  application:
    name: back-hexagonal
  datasource:
    url: jdbc:mysql://localhost:3306/testedb?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
